# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

books =  [
    {:isbn => '9780806539966', :title => 'Wizard: The Life and Times of Nikola Tesla : Biography of a Genius', :author => 'Seifer, Marc J.', :publisher => 'Citadel Pr', :summary => 'The story of one of the most prolific, independent, and iconoclastic inventors of this century . . . fascinating', :publication_year => '2016', :category => 'Science & Technology', :edition => 'Reprint', :search_count => 10},
    {:isbn => '9780763676193', :title => 'Monsters of Men', :author => 'Patrick Ness', :publisher => 'Candlewick Press (MA)', :summary => 'As a world-ending war surges around them, Todd and Viola face monstrous decisions. The indigenous Spackle, thinking and acting as one, have mobilized to avenge their murdered people. Ruthless human leaders prepare to defend their factions at all costs, even as a convoy of new settlers approaches. And as the ceaseless Noise lays all thoughts bare, the projected will of the few threatens to overwhelm the desperate desire of the many.', :publication_year => '2014', :category => 'Adventure', :edition => '2nd', :search_count => 10},
    {:isbn => '9781285740621', :title => 'Calculus', :author => 'James Stewart', :publisher => 'Cengage Learning', :summary => "James Stewart's CALCULUS texts are widely renowned for their mathematical precision and accuracy, clarity of exposition, and outstanding examples and problem sets. Millions of students worldwide have explored calculus through Stewart's trademark style, while instructors have turned to his approach time and time again. In the Eighth Edition of CALCULUS, Stewart continues to set the standard for the course while adding carefully revised content. The patient explanations, superb exercises, focus on problem solving, and carefully graded problem sets that have made Stewart's texts best-sellers continue to provide a strong foundation for the Eighth Edition. From the most unprepared student to the most mathematically gifted, Stewart's writing and presentation serve to enhance understanding and build confidence.", :publication_year => '2015', :category => 'Science & Mathematics', :edition => '8th', :search_count => 8},
    {:isbn => '9781771642484', :title => 'The Hidden Life of Trees: What They Feel, How They Communicate—Discoveries from a Secret World', :author => 'Peter Wohlleben', :publisher => 'Greystone Books', :summary => "Are trees social beings? In this international bestseller, forester and author Peter Wohlleben convincingly makes the case that, yes, the forest is a social network. He draws on groundbreaking scientific discoveries to describe how trees are like human families: tree parents live together with their children, communicate with them, support them as they grow, share nutrients with those who are sick or struggling, and even warn each other of impending dangers. Wohlleben also shares his deep love of woods and forests, explaining the amazing processes of life, death, and regeneration he has observed in his woodland.", :publication_year => '2016', :category => 'Science & Mathematics', :edition => '1st', :search_count => 9},
    {:isbn => '9781119293491', :title => 'Calculus For Dummies', :author => 'Mark Ryan', :publisher => 'For Dummies', :summary => "Calculus For Dummies, 2nd Edition makes calculus manageable—even if you're one of the many students who sweat at the thought of it. By breaking down differentiation and integration into digestible concepts, this guide helps you build a stronger foundation with a solid understanding of the big ideas at work. This user-friendly math book leads you step-by-step through each concept, operation, and solution, explaining the 'how' and 'why' in plain English instead of math-speak. Through relevant instruction and practical examples, you'll soon learn that real-life calculus isn't nearly the monster it's made out to be.", :publication_year => '2016', :category => 'Science & Mathematics', :edition => '2nd', :search_count => 1},
    {:isbn => '9781438004976', :title => "Barron's AP Calculus", :author => 'David Bock M.S.', :publisher => "Barron's Educational Series", :summary => "Both Calculus AB and Calculus BC are covered in this comprehensive AP test preparation manual. The book's main features include: Four practice exams in Calculus AB and four more in Calculus BC, All test questions answered with solutions explained, A detailed subject review covering topics for both exams, Advice to students on efficient use of their graphing calculators, The manual can be purchased alone or with an optional CD-ROM presenting two more practice tests with answers. One test is in Calculus AB, and the other in Calculus BC.", :publication_year => '2015', :category => 'Science & Mathematics', :edition => '13th', :search_count => 2},
  	 ]

books.each do |book|
  Book.create!(book)
end 

User.create!(:email => "admin@gmail.com", :first_name => "Default", :last_name => "Admin", :password => "123456", :password_confirmation => "123456", :position => "Admin")
User.create!(:email => "staff@gmail.com", :first_name => "Default", :last_name => "Staff", :password => "123456", :password_confirmation => "123456", :position => "Staff")
User.create!(:email => "user@gmail.com", :first_name => "Default", :last_name => "User", :password => "123456", :password_confirmation => "123456", :position => "User")

Role.create!(:position => "Staff", :position_code => "Staff1")
Role.create!(:position => "Admin", :position_code => "Admin1")